apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
spec:
  selector:
    app: cicd-demo
  type: NodePort
  ports:
    - port: 3000        
      targetPort: 3000  
      nodePort: 30001   
