apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
spec:
  type: NodePort
  selector:
    app: cicd-demo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
