name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./cicd-demo
        run: npm install

      - name: Run tests
        working-directory: ./cicd-demo
        run: npm test --ci --runInBand

      - name: Verify Dockerfile exists
        run: |
          ls -la ./cicd-demo/
          test -f "./cicd-demo/Dockerfile"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: meta
        run: |
          echo "TAG=${{ secrets.DOCKERHUB_USERNAME }}/cicd-demo:latest" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./cicd-demo
          file: ./cicd-demo/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.TAG }}
          provenance: false  # keeps manifest simple for some setups
